### ISSUE TITLE
Password Reset Link is dead.

### ISSUE THREAD

**Issue by Lifebario** [Lifebar/support#12]
Submitter: Paul-Jules Micolet

Currently if you request a new password the email you receive gives you a link that leads to nowhere, I get a "Sorry, the website material.polygonalweave.com cannot be found." message.

**Comment by rewphus** [comment]
Thank you for letting us know about this.  We will make sure to get that resolved right away.

**Comment by rewphus** [comment]
We believe we have the link working now, but during my testing I did find the workflow is a little wonky.  Hopefully we can get the smoothed over soon, but in the meantime, at least the links work now, right?
