### ISSUE TITLE
Maybe hide user email addresses when they submit a bug/suggestion

### ISSUE THREAD

**Issue by pjmicolet** [Lifebar/support#14]
Hey I was just wondering, it may be best if user email addresses don't show up here on the bug tracker. I can imagine some people could be annoyed to find out that their email addresses are being published here publicly. I might just be making up a problem though.
Cheers

**Comment by rewphus** [comment]
No, you are absolutely right, unfortunately there is no automated way to do that at the moment. I will take them off manually for now and look in to not showing them at all. Thanks for the heads up!

**Comment by rewphus** [comment]
We've done the best we can do for now, and are now pre-filling the bug report with the username from Lifebar as well as a message in email to skip, so hopefully that will alleviate this issue until we can find a more elegant solution.
