### ISSUE TITLE
Series duplicates

### ISSUE THREAD

**Issue by pjmicolet** [Lifebar/support#15]
Not a big problem and I doubt you have much control over this (most likely some problem with the crawler) but I seem to have 2 "You don't know jack" series on my profile page. I guess this will also happen somewhere else, just wanted you to know.
![untitled](https://cloud.githubusercontent.com/assets/1353391/12357567/6621f404-bba0-11e5-9c7d-e3ba9215297a.png)

**Comment by rewphus** [comment]
Good eye.  I'll have to have @katet19 look at it, but we should be able to resolve that.

**Comment by rewphus** [comment]
We believe we have this resolved now.  Let us know if you see this pop up again.

**Comment by pjmicolet** [comment]
Hey, it might have been fixed though I think the issue might have been caused by the fact that Jackbox Party Pack 2 is not included in the "You Don't Know Jack" series. If you click on the series right now you should see that the first one is included but not the second.
