### ISSUE TITLE
0 Followers breaks activity tab

### ISSUE THREAD

**Issue by Lifebario** [Lifebar/support#7]
Submitter: Cameron

Once I stopped following the original 10 critics I get the following error when I click on the activity tab: "Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /home/polygo6/public_html/php/controller_event.php on line 79"

**Comment by rewphus** [comment]
Thanks for reporting this. We will get on it right away.

**Comment by katet19** [comment]
This should be fixed now. If there isn't activity to be found the tab will display nothing at the moment, instead of an error message. Thanks for letting us know about the error!
