### ISSUE TITLE
Gameboy games currently linking back to N64

### ISSUE THREAD

**Issue by Lifebario** [Lifebar/support#9]
Submitter: paul

Might just be me, but currently if I click on the Game Boy icon on my profile it just lists my N64 games.

**Comment by rewphus** [comment]
It's not just you, we have seen the platform lists in the profile act up before.  We will make sure to take a look at it and let you know when it's resolved.

**Comment by pjmicolet** [comment]
Cool, thanks for that (this is OP btw)

**Comment by rewphus** [comment]
I think we finally have this figured out now.  I'll leave it open for a bit just in case, so let us know if you are still seeing incorrect results.
